//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PepDogWebsite.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class UserDetails
    {
        public int ID { get; set; }
		[StringLength(50)]
		public string Name { get; set; }
		[StringLength(300)]
		public string Email { get; set; }
		[StringLength(300)]
		public string Password { get; set; }
    }
}
